/**:
  ros__parameters:
    operation_mode: "control"
    driver_device: "waveshare_driver"
    com_port: "/dev/ttyUSB0"
    pwm_min: 0
    pwm_max: 4095
    angle_min: 0
    angle_software_min: 0
    angle_max: 360
    angle_software_max: 360
    speed_max: 200

/servo_pan/servo_pan:
  ros__parameters:
    servo_id: 8
    angle_software_min: 115
    angle_software_max: 230
    dir: -1

/servo_tilt/servo_tilt:
  ros__parameters:
    servo_id: 9
    angle_software_min: 115
    angle_software_max: 230
    dir: 1
